version: '3.8'
services:
  dre:
    build: .
    environment:
      APPSYNC_KEY: "${APPSYNC_KEY}"
      NODE_JWK_KEY: "${NODE_JWK_KEY}"
      STREAMR_STREAM_ID: "${STREAMR_STREAM_ID}"
      PUBSUB_TYPE: "${PUBSUB_TYPE:-streamr}"
      GW_PORT: "${GW_PORT}"
      GW_HOST: "${GW_HOST}"
      GW_USERNAME: "${GW_USERNAME}"
      GW_PASSWORD: "${GW_PASSWORD}"
      GW_TLS: "${GW_TLS}"
      GW_ENABLE_OFFLINE_QUEUE: "${GW_ENABLE_OFFLINE_QUEUE}"
      GW_LAZY_CONNECT: "${GW_LAZY_CONNECT}"
      BULLMQ_PORT: "${BULLMQ_PORT}"
      BULLMQ_HOST: "${BULLMQ_HOST:-cache}"
      BULLMQ_USERNAME: "${BULLMQ_USERNAME}"
      BULLMQ_PASSWORD: "${BULLMQ_PASSWORD}"
      BULLMQ_TLS: "${BULLMQ_TLS}"
      BULLMQ_ENABLE_OFFLINE_QUEUE: "${BULLMQ_ENABLE_OFFLINE_QUEUE}"
      BULLMQ_LAZY_CONNECT: "${BULLMQ_LAZY_CONNECT}"
      WORKERS_REGISTER: "${WORKERS_REGISTER}"
      WORKERS_UPDATE: "${WORKERS_UPDATE}"
      WORKERS_JOB_ID_REFRESH_SECONDS: "${WORKERS_JOB_ID_REFRESH_SECONDS}"
      WORKERS_MAX_FAILURES: "${WORKERS_MAX_FAILURES}"

    volumes:
      - dre-sqlite:/app/sqlite
      - dre-cache:/app/cache
  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --maxmemory-policy noeviction
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
  dre-sqlite:
    driver: local
  dre-cache:
    driver: local
