version: '3.8'
services:
  dre:
    image: "warpredstone/dre:${DRE_IMAGE_TAG:-latest}"
    restart: always
    env_file:
      - .env
    environment:
      BULLMQ_HOST: "${BULLMQ_HOST:-bullmq}"
    ports:
      - '80:8080'

    volumes:
      - dre-cache:/app/sqlite
      - warp-cache:/app/cache
  bullmq:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    command: redis-server --save 20 1 --loglevel warning --maxmemory-policy noeviction
    volumes:
      - bullmq-cache:/data
volumes:
  bullmq-cache:
    driver: local
  dre-cache:
    driver: local
  warp-cache:
    driver: local
