name: Create Release
# Update patch version by default. 
# Use (MAJOR) or (MINOR) in the commit if you want to update corresponding version

on:
  pull_request: # delete
    
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        required: false
        default: true     

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          short_tags: false

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.version.outputs.version_tag }}
          prerelease: ${{ inputs.prerelease }}
          title: Release ${{ steps.version.outputs.version_tag }}
          files: |
            docker-compose.yml
            
