name: Create Release

on:
  pull_request: # delete
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        required: false
        default: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          short_tags: false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          release_name: Release ${{ steps.version.outputs.version_tag }}
          draft: false
          prerelease: ${{ inputs.prerelease }}
